Tickets/preops 1246
lsst/dp0-2_lsst_io pull request #69
Opened 2023-03-16 21:12 UTC by Madejski

2023-03-20 14:32 UTC, ChristinaAdair requested changes
Only got through Part A

2023-03-20 14:32 UTC, ChristinaAdair commented on tutorials-examples/portal-4.rst
A1.4 "You should leave the "Output Column"... maybe explain in the large table to the right?

2023-03-20 14:32 UTC, ChristinaAdair commented on tutorials-examples/portal-4.rst
A2.1 "an" should be "a"

2023-03-20 14:32 UTC, ChristinaAdair commented on tutorials-examples/portal-4.rst
A2.2 "bottom" has an extra letter

2023-03-20 14:32 UTC, ChristinaAdair commented on tutorials-examples/portal-4.rst
A3.1 you put "100" in the text, but the image shows "50"

2023-03-20 18:52 UTC, ChristinaAdair commented on tutorials-examples/portal-4.rst
B1.1 "simple" typo

2023-03-20 18:55 UTC, ChristinaAdair commented on tutorials-examples/portal-4.rst
B2.1 "To" typo

2023-03-20 18:58 UTC, ChristinaAdair commented on tutorials-examples/portal-4.rst
B3.1, maybe include a picture with the "log" option selected in chart options section?

2023-03-20 19:02 UTC, ChristinaAdair requested changes
reviewed part A and B, some comments and suggestions for changes

2023-03-30 22:36 UTC, Madejski commented on tutorials-examples/portal-4.rst
done

2023-03-30 22:37 UTC, Madejski commented on tutorials-examples/portal-4.rst
done

2023-03-30 23:04 UTC, Madejski commented on tutorials-examples/portal-4.rst
done

2023-03-30 23:05 UTC, Madejski commented on tutorials-examples/portal-4.rst
done

2023-03-30 23:06 UTC, Madejski commented on tutorials-examples/portal-4.rst
fixed!

2023-03-30 23:22 UTC, Madejski commented on tutorials-examples/portal-4.rst
Very helpful!  I wasn't clear there..

2023-03-30 23:23 UTC, Madejski commented on tutorials-examples/portal-4.rst
very helpful - I wasn't clear there.

2023-03-30 23:25 UTC, Madejski commented on tutorials-examples/portal-4.rst
OK

2023-03-30 23:26 UTC, Madejski commented on tutorials-examples/portal-4.rst
done

2023-04-27 00:31 UTC, Madejski commented on tutorials-examples/portal-4.rst
OK

2023-05-25 05:01 UTC, MelissaGraham approved these changes
Made a bunch of final commits to get through all requested changes, will leave record in the Jira ticket.

2023-05-25 05:03 UTC, merged